##############
### local
##############

server:
  port: 8088

spring:
  datasource:    
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari: 
      pool-name: hikari-cp
      maximum-pool-size: 30
      minimum-idle: 2
      data-source-properties: 
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true
  jpa:    
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    hibernate:
        ddl-auto: none  

logging:
  level:  
    com.example.sampleapi: info 
